USE KODILLA_COURSE;

CREATE TABLE STATS (
STAT_ID INT(11) AUTO_INCREMENT,
STAT_DATE DATETIME NOT NULL,
STAT VARCHAR(20) NOT NULL,
VALUE INT(11) NOT NULL,
PRIMARY KEY ( STAT_ID )
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS QTY FROM BOOKS
WHERE BESTSELLER = TRUE;

DELIMITER $$
CREATE EVENT UPDATE_STATS
ON SCHEDULE EVERY 1 MINUTE
DO
BEGIN
  DECLARE QTYVALUE INT DEFAULT 0;
  SELECT QTY FROM BESTSELLERS_COUNT INTO QTYVALUE;
  CALL UpdateBestSellers();  
  INSERT INTO STATS (STAT_DATE, STAT, VALUE) 
  VALUES (CURDATE(), "BESTSELLERS", QTYVALUE);  
END $$ 
DELIMITER ; 